version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/test

workflows:
  main:
    jobs:
      - build
