version: 2.1

orbs:
  python: circleci/python@0.3.2
  terraform: circleci/terraform@1.0.1

jobs:
  build:
    executor: python/default
    parameters:
      test_results_path:
        default: .
        description: path to the JUnit-style test results XML file
        type: string
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pytest --junitxml=<< parameters.test_results_path >>/test-results.xml
          name: Test
      - store_test_results:
          path: << parameters.test_results_path >>

workflows:
  main:
    jobs:
      - build
      - terraform/fmt:
          checkout: true
          path: ./terraform
